### ISSUE TITLE
Question about using rtdsc

### ISSUE THREAD

**Issue by cychong47** [Gandi/packet-journey#9]
Hello,

Is there any reason to dedicate one core for rdtsc read operation?

**Comment by baloo** [comment]
Hello,

The rdtsc actually runs on the same core as the control thread (the thread responsible of keeping lpm and neighbor tables in pktj in sync with the kernel' tables).
see https://github.com/Gandi/packet-journey/blob/b2aca2f905745d610aee01e1c0b0088662d3d6d0/app/main.c#L2201-L2218

**Comment by cychong47** [comment]
Okay I see.

Why not each core get the TSC value in each loop? Have concern about rdtsc read overhead for each forwarding core? 1ms granularity (1000 usleep in rdtsc_thread) has no issue in performance?

**Comment by fatih-acar** [comment]
Hi,

Yes, as you said we had a concern about getting the value in each forwarding thread, it had an impact on performance.
The granularity you pointed out should not have any impact. It only adds a 1ms latency in case you have packets that have been buffered (which should not happen often). See: https://github.com/Gandi/packet-journey/blob/master/app/main.c#L1257

**Comment by cychong47** [comment]
Thanks for the answer
